"""empty message

Revision ID: 911f1165630f
Revises: f7eefc9cf1af
Create Date: 2020-11-19 04:42:13.368399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911f1165630f'
down_revision = 'f7eefc9cf1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
